// <auto-generated />
namespace WebDev.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WebDev1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebDev1));
        
        string IMigrationMetadata.Id
        {
            get { return "201612071030333_WebDev1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
